In [ ]:
#Theoretical Questions:
#1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
#= The purpose of Numpy is to increase the performance of codes(like Arithmatic operations). because c is the fastest computation after c++ and and Numpy array build from c.
# and numpy is homogenous that's why the performance or computation is increased.

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
#=Average can be defined as the sum of all the numbers divided by the total number of values. A mean is defined as the mathematical average of the set of two or more data values.
# Average is usually defined as mean or arithmetic mean. Mean is simply a method of describing the average of the sample.

In [ ]:
#3.  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# = Reversing a NumPy array along different axes can be done using array slicing or the flip function.The methods allow for reversing the order of elements along axis


In [ ]:
# 1D array ex-
import numpy as np
arr=np.array([1,2,3])
arr

In [ ]:
arr[::-1]

array([3, 2, 1])

In [ ]:
#2d array
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.flip(arr1,axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.flip(arr1,axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
#= In NumPy, we can determine the data type (dtype) of the elements in an array using the dtype attribute of the array.
 #This attribute provides information about the type of the elements in the array, such as integers, floats
 #This data type object (dtype) provides information about the layout of the array.

In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
#In NumPy, an ndarray (short for N-dimensional array) is the central data structure used to store homogeneous collections of elements (i.e., all elements must be of the same data type).
#Key Features-Homogeneous Data Types,Fixed Size,Element-wise Operations,Shape and Reshaping ,Broadcasting



In [ ]:
#6.  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
# = When dealing with large-scale numerical operations, the performance differences between NumPy arrays and Python lists become significant. NumPy is specifically designed for efficient numerical computing
#python list store hetrogenous data that's why the performance is slow in large-scale data because we don't know that where is our data stored
 # and numpy store homogenous data  and due to same data type the performance is increase

In [ ]:
#7.  Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
#In NumPy, vstack() and hstack() are functions used for stacking arrays along different axes.
# They allow you to combine multiple arrays into a single array either vertically or horizontally.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [ ]:
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
#The fliplr() function flips the array left to right, reversing the order of elements along axis 1 (the horizontal axis, corresponding to columns)
#The flipud() function flips the array up to down, reversing the order of elements along axis 0 (the vertical axis, corresponding to rows).

In [ ]:
#9. . Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
#e array_split() function in NumPy is used to split an array into multiple sub-arrays along a specified axis.
# This function is particularly useful when you want to divide a large array into smaller chunks, which can be processed separately.

In [ ]:
#10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
#Vectorization refers to the ability of NumPy to perform element-wise operations on entire arrays without the need for explicit loops.
# Instead of iterating through elements in Python for each operation
#Broadcasting is a set of rules that NumPy follows to perform operations on arrays of different shapes.
 #Instead of requiring arrays to have the same shape for element-wise operations,
 #NumPy will automatically "broadcast" smaller arrays across the larger array so that the operation can be performed.

In [1]:
#Practical Questions:
#1.  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
import numpy as np
import random
ar=np.random.randint(1,100,(3,3))
ar

array([[38, 53, 52],
       [99, 14, 53],
       [87, 47, 38]])

In [ ]:
ar[::-1]

array([[54, 75, 81],
       [48, 66, 62],
       [38, 81, 91]])

In [ ]:
ar.T

array([[38, 48, 54],
       [81, 66, 75],
       [91, 62, 81]])

In [ ]:
#2  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
r=np.arange(1,11)
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
r.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
r.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#3.  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
ra=np.random.random((4,4))
ar=np.pad(ra,pad_width=1 , mode='constant', constant_values=0)
print(ar)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.43859102 0.7539097  0.91824347 0.95127353 0.        ]
 [0.         0.68612244 0.30657717 0.42853717 0.15773642 0.        ]
 [0.         0.04599813 0.73497648 0.85607543 0.53974308 0.        ]
 [0.         0.58130375 0.23835766 0.42571344 0.62274394 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [2]:
#4.  Using NumPy, create an array of integers from 10 to 60 with a step of 5
np.arange(10,61,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [20]:
#5.  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
arr=np.array( ('python', 'numpy', 'pandas'))
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [19]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [21]:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [22]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [33]:
#6.Generate a NumPy array of words. Insert a space between each character of every word in the array
char=np.fromstring("Rahul  Meel",sep=" ")
char

<ipython-input-33-ded67983298f>:2: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  char=np.fromstring("Rahul  Meel",sep=" ")


array([], dtype=float64)

In [38]:
ch=np.array('Rahul Meel')
np.char.join(" ", ch)

array('R a h u l   M e e l', dtype='<U19')

In [45]:
#7.  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[5,8,3],[4,7,6]])


In [47]:
arr1+arr2

array([[ 6, 10,  6],
       [ 8, 12, 12]])

In [48]:
arr1-arr2

array([[-4, -6,  0],
       [ 0, -2,  0]])

In [49]:
arr1*arr2

array([[ 5, 16,  9],
       [16, 35, 36]])

In [50]:
arr1/arr2

array([[0.2       , 0.25      , 1.        ],
       [1.        , 0.71428571, 1.        ]])

In [54]:
 #8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [56]:
n=np.eye(5,5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
np.diagonal(n)

array([1., 1., 1., 1., 1.])

In [80]:
#9.  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import random
r=np.random.randint(0,1000,size=100)
def is_prime(r):
  if n<=1:
    return False
  for i in r:
    if r/i==0:
      return False

  return True

  prime_numbers=[num for num in r if is_prime(num)]

r,prime_numbers

(array([489, 946, 359, 151,  79, 946, 365,  84, 772, 621, 815, 320, 648,
         81, 861, 719, 664, 581, 182, 709, 973, 420, 338, 860, 702, 221,
        236,  11,  32, 505, 204, 239, 344, 438, 400, 851, 545, 550, 344,
        206, 411, 636, 811, 363, 667, 303, 816, 955, 907, 489, 580, 710,
        187, 826, 207, 994, 256, 742, 247, 663, 157, 799, 562, 272, 851,
        656, 506, 547, 754, 825,  33, 337, 134, 491, 876, 296, 102, 817,
        871,  99, 895, 675, 169,   1, 306, 944, 719, 681, 850, 421, 178,
        663, 179, 906,  36, 612, 983, 714, 656, 370]),
 [431,
  359,
  3,
  139,
  421,
  379,
  547,
  251,
  643,
  263,
  929,
  127,
  389,
  179,
  599,
  269,
  17,
  257,
  163,
  17])

In [80]:
#10.  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [118]:
daily=np.random.randint(15,31 ,size=30)
week= np.random.randint(15,31,size=(4,7))



av=week.mean(axis=0)

In [110]:
daily


array([28, 24, 30, 19, 20, 20, 15, 30, 28, 20, 29, 16, 17, 15, 20, 23, 27,
       19, 28, 21, 15, 26, 29, 15, 30, 28, 15, 19, 22, 16])

In [111]:
week

array([[25, 21, 21, 25, 24, 20, 24],
       [29, 23, 24, 19, 20, 24, 15],
       [30, 19, 22, 29, 28, 21, 17],
       [23, 23, 21, 18, 19, 26, 16]])

In [119]:
av


array([23.  , 24.25, 23.  , 20.75, 22.25, 23.5 , 22.75])